modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "https://github.com/vectorwing/FarmersDelight/issues"
license="${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/vectorwing/FarmersDelight"
logoFile = "logo.png"
logoBlur = false
credits = "Chloe Dawn, Grimmauld, CDAGaming, TelepathicGrunt, XFactHD, GizmoThemoonPig, ConductiveFoam, simibubi, MerchantPug, Jozufozu, bagel, Silk, SkySom, Eutro, RaymondBlaze and many others!"
authors = "${mod_authors}"
description = "A cozy farming and cooking expansion for Minecraft!"
enumExtensions="META-INF/enumextensions.json"
## Catalogue mod compatibility
itemIcon = "farmersdelight:stove"
configBackground = "minecraft:textures/block/bricks.png"

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange="${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "crafttweaker"
    type = "optional"
    versionRange = "[14.0.6,)"
    ordering = "NONE"
    side = "BOTH"
